name: Docker Image CI

on:
  push:
    branches: [ "subfolder" ]
  pull_request:
    branches: [ "subfolder" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag openwebui_subfolder:$(date +%s)
